### PR TITLE
Add TypeScript types, and minimize bundle size

### PR DESCRIPTION
**Pull request by grantila**
Thanks for a great library!

I've used this in [`edit-json`](https://github.com/grantila/edit-json) and added the types manually there, but it makes more sense to ship it with the library itself.

The types here are what I find reasonable and useful, but feel free to add/remove/rename if you feel it makes more sense.

### CODE REVIEW

**Comment by finnp** [comment]
Thank you. If you are interested I can also add you as a contributor.

**Comment by grantila** [comment]
It's fine, but thanks. If I want/need more work on it, we can take it from there. I think this package is pretty stable as-is and doubt much more work will be needed on it from my side. 👍

**Comment by finnp** [comment]
Published it as 1.2.0. Let me know if there are any issues 👍

**Comment by finnp** [comment]
@grantila By the way, the original purpose of this was actually for in-place json editing :) Created it back then for Greenkeeper, here's the module: https://www.npmjs.com/package/json-in-place

**Pull request merged**
